language: ruby
rvm:
  - 2.4.0

services:
  - postgresql
addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database planning_poker_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
