# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  # when blank, defaults to redis://localhost:6379
  url: <%= ENV['REDIS_URL'] %>

development:
  adapter: async

test:
  adapter: async
